name: Ping WForst-Breeze
on:
    schedule:
      - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
            pip install beautifulsoup4
            pip install lxml
            python WForst-Breeze.py