# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
name: Ping WForst-Breeze

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:
  schedule:
        - cron: '*/2 * * * *' # 每分钟运行一次
jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: | 
            pip install beautifulsoup4
            pip install lxml

      - name: Ping
        run: python WForst-Breeze.py
        timeout-minutes: 1